nohup time bin/Tracks --process CeMinus --rmue 3e-17 --ntrks 100000 --mustopsfile Mu2eIIa2_m50_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtm50 --targetfile Data/Mu2e2Target_m50.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigCeMinus_tgtm50.log &
nohup time bin/Tracks --process FlatDIO --ntrks 1000000 --mustopsfile Mu2eIIa2_m50_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtm50 --targetfile Data/Mu2e2Target_m50.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigFlatDIO_tgtm50.log &
nohup time bin/Tracks --process CeMinus --rmue 3e-17 --ntrks 100000 --mustopsfile Mu2eIIa2_m25_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtm25 --targetfile Data/Mu2e2Target_m25.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigCeMinus_tgtm25.log &
nohup time bin/Tracks --process FlatDIO --ntrks 1000000 --mustopsfile Mu2eIIa2_m25_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtm25 --targetfile Data/Mu2e2Target_m25.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigFlatDIO_tgtm25.log &
nohup time bin/Tracks --process CeMinus --rmue 3e-17 --ntrks 100000 --mustopsfile Mu2eIIa2_m10_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtm10 --targetfile Data/Mu2e2Target_m10.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigCeMinus_tgtm10.log &
nohup time bin/Tracks --process FlatDIO --ntrks 1000000 --mustopsfile Mu2eIIa2_m10_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtm10 --targetfile Data/Mu2e2Target_m10.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigFlatDIO_tgtm10.log &
nohup time bin/Tracks --process CeMinus --rmue 3e-17 --ntrks 100000 --mustopsfile Mu2eIIa2_p10_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtp10 --targetfile Data/Mu2e2Target_p10.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigCeMinus_tgtp10.log &
nohup time bin/Tracks --process FlatDIO --ntrks 1000000 --mustopsfile Mu2eIIa2_p10_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtp10 --targetfile Data/Mu2e2Target_p10.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigFlatDIO_tgtp10.log &
nohup time bin/Tracks --process CeMinus --rmue 3e-17 --ntrks 100000 --mustopsfile Mu2eIIa2_p25_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtp25 --targetfile Data/Mu2e2Target_p25.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigCeMinus_tgtp25.log &
nohup time bin/Tracks --process FlatDIO --ntrks 1000000 --mustopsfile Mu2eIIa2_p25_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtp25 --targetfile Data/Mu2e2Target_p25.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigFlatDIO_tgtp25.log &
nohup time bin/Tracks --process CeMinus --rmue 3e-17 --ntrks 100000 --mustopsfile Mu2eIIa2_p50_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtp50 --targetfile Data/Mu2e2Target_p50.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigCeMinus_tgtp50.log &
nohup time bin/Tracks --process FlatDIO --ntrks 1000000 --mustopsfile Mu2eIIa2_p50_ --npot 1.3e22 --tfile Mu2e2DriftAmbig_tgtp50 --targetfile Data/Mu2e2Target_p50.dat --trackerfile Data/Mu2e2Tracker.dat --ipafile Data/Mu2e2_IPA.dat --calofile Data/Mu2e2Calo.dat --fitschedule Schedule_driftfit.txt >& Mu2e2DriftAmbigFlatDIO_tgtp50.log &

